name: Preparing to patch
runs:
  using: "composite"
  steps:
    - name: Set up jdk
      uses: actions/setup-java@v4.5.0
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
#    - name: Setup Cloudflare Warp
#      shell: bash
#      run: bash src/etc/cf_warp.sh
    - name: Install dependencies
      shell: bash
      run: |
        npm install --omit=dev --no-fund --no-audit \
          apkmirror-downloader@latest \
          @revanced/cli@latest \
          ua-parser-js
