name: Releasing APK files
runs:
  using: "composite"
  steps:
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          ./release/*.apk
        name: Revanced & Revanced Extended
        tag: all
        allowUpdates: true
