name: Build and Release
permissions: write-all

on:
  schedule:
    - cron: "0 9 * * *"  # Run daily at 9 AM UTC
  workflow_dispatch:
    inputs:
      target:
        description: 'Build target'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - youtube-anddea
          - twitter-piko
          - instagram-experiments
          - googlephotos
          - soundcloud

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - id: check
        run: bash src/ci/check.sh

  build:
    needs: prepare
    if: needs.prepare.outputs.should_build == 'true' || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        include:
          - target: youtube-anddea
            script: Anddea-Revanced-Extended.sh
            app: youtube
          - target: twitter-piko
            script: Piko.sh
            app: twitter
          - target: instagram-experiments
            script: Revanced-Experiment.sh
            app: instagram
          - target: googlephotos
            script: Revanced.sh
            app: googlephotos
          - target: soundcloud
            script: Revanced.sh
            app: soundcloud
        target: ${{ fromJSON(github.event.inputs.target == 'all' && '["youtube-anddea", "twitter-piko", "instagram-experiments", "googlephotos", "soundcloud"]' || format('["%s"]', github.event.inputs.target)) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Build ${{ matrix.target }}
        run: bash src/build/${{ matrix.script }} ${{ matrix.app }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-artifacts
          path: |
            release/*.apk
            release/versions.txt

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get version info
          version_file=$(find artifacts -name "versions.txt" | head -n 1)
          youtube_version=$(grep "youtube=" "$version_file" | cut -d'=' -f2 || echo "N/A")
          twitter_version=$(grep "twitter=" "$version_file" | cut -d'=' -f2 || echo "N/A")
          instagram_version=$(grep "instagram=" "$version_file" | cut -d'=' -f2 || echo "N/A")
          photos_version=$(grep "google-photos=" "$version_file" | cut -d'=' -f2 || echo "N/A")
          soundcloud_version=$(grep "soundcloud=" "$version_file" | cut -d'=' -f2 || echo "N/A")
          
          # Create release notes
          release_notes="### Versions\n"
          [ "$youtube_version" != "N/A" ] && release_notes+="- YouTube (Anddea): $youtube_version\n"
          [ "$twitter_version" != "N/A" ] && release_notes+="- Twitter (Piko): $twitter_version\n"
          [ "$instagram_version" != "N/A" ] && release_notes+="- Instagram (Experiments): $instagram_version\n"
          [ "$photos_version" != "N/A" ] && release_notes+="- Google Photos (ReVanced): $photos_version\n"
          [ "$soundcloud_version" != "N/A" ] && release_notes+="- SoundCloud (ReVanced): $soundcloud_version\n"
          
          # Create release
          release_tag="v$(date +'%Y.%m.%d')"
          gh release create "$release_tag" \
            --title "Release $release_tag" \
            --notes "$release_notes" \
            artifacts/**/*.apk
